services:
  pagamento-db:
    image: postgres:latest
    container_name: pagamento-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: api_pagamento_db
    ports:
      - "5432:5432"
    networks:
      - redelocal

networks:
  redelocal:

volumes:
  postgres-data:
