CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS tb_transaction(
    id              INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    payer           BIGINT,
    payee           BIGINT,
    value           BIGINT,
    createdAt       TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tb_wallets(
    id                      INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fullName                VARCHAR,
    cpfCnpj                 VARCHAR,
    email                   VARCHAR,
    password                VARCHAR,
    type                    INT,
    balance                 BIGINT
);

CREATE UNIQUE INDEX IF NOT EXISTS cpfCnpj_idx ON tb_wallets (cpfCnpj);
CREATE UNIQUE INDEX IF NOT EXISTS email_idx ON tb_wallets (email);

CREATE TABLE IF NOT EXISTS tb_notification(
    message BOOLEAN
);

ALTER TABLE tb_transaction
    ADD CONSTRAINT fk_payer FOREIGN KEY (id) REFERENCES tb_wallets(id),
    ADD CONSTRAINT fk_payee FOREIGN KEY (id) REFERENCES tb_wallets(id);